---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: client1-dev-team
  namespace: apps
spec:
  interval: 1m0s
  ref:
    branch: dev-team
  url: https://github.com/fluxcd/flux2-multi-tenancy
